const Sdata = {
  shopItems: [
    {
      id: 6,
      discount: 50,
      cover: "./images/products/balo11.1.jpg",
      name: "Nón Y2010",
      price: 100,
    },
      {
        id: 7,
        discount: 50,
        cover: "./images/products/phukien9.2.jpg",
        name: "Nón Y2010",
        price: 100,
      },
      {
        id: 5,
        discount: 50,
        cover: "./images/products/balo10.1.jpg",
        name: "Balo đi học ",
        price: 100,
      },
      {
        id: 7,
        discount: 50,
        cover: "./images/products/phukien5.jpg",
        name: "Nón Y2010",
        price: 100,
      },
    {
      id: 7,
      discount: 50,
      cover: "./images/products/phukien5.3.jpg",
      name: "Nón Y2010",
      price: 100,
    },
    {
      id: 7,
      discount: 50,
      cover: "./images/products/phukien6.2.jpg",
      name: "Nón Y2010",
      price: 100,
    },
    {
      id: 7,
      discount: 50,
      cover: "./images/products/phukien7.jpg",
      name: "Bóp nam ",
      price: 100,
    },
    {
      id: 7,
      discount: 50,
      cover: "./images/products/phukien9.2.jpg",
      name: "Nón Y2010",
      price: 100,
    },
    {
      id: 7,
      discount: 50,
      cover: "./images/products/phukien9.2.jpg",
      name: "Nón Y2010",
      price: 100,
    },
    {
      id: 16,
      cover: "./images/products/phukien3.jpg",
      name: "nón cụp",
      price: "5",
      discount: "2",
    },
    {
      id: 7,
      discount: 50,
      cover: "./images/products/phukien1.jpg",
      name: "Nón Y2010",
      price: 100,
    },
    {
      id: 7,
      discount: 50,
      cover: "./images/products/phukien2.jpg",
      name: "Nón Y2010",
      price: 100,
    },
  ],
}
export default Sdata
